### PR TITLE
support for handling bibtex' @string

### PR DESCRIPTION
**Pull request by malb**
This PR adds initial support for `@string` cf. #133 

It probably needs some refinement as my elisp isn't that great. Also, parsebib does not support bibtex string concatenation so entries like

```
@string{pkc14name =             "PKC~2014" # pkcname_v2}
```

found in [cryptobib](https://cryptobib.di.ens.fr) won't work.

### CODE REVIEW

**Comment by tmalsburg** [comment]
Hi @malb, thanks for making this PR and sorry for the slow response. I'm busy with teaching. I will send some comments later this week (hopefully).

**Comment by malb** [comment]
No worries, I can relate :)

**Comment by tmalsburg** [comment]
Hi, this is a useful feature but I still think that string resolution should be handled by the API used of parsing BibTeX.  Would you mind creating an issue in [parsebib](https://github.com/joostkremers/parsebib/issues)?

**Comment by tmalsburg** [comment]
Perhaps we should consider switching to bibtex.el for parsing? We'd lose a dependency and according to Kremers, bibtex.el is more sophisticated.

**Comment by malb** [comment]
I've updated this PR to use https://github.com/joostkremers/parsebib/pull/6 It is indeed quite a bit cleaner.

**Comment by tmalsburg** [comment]
Great. I'll merge it once your PR for parsebib is closed. 

On March 8, 2017 10:48:32 AM EST, Martin Albrecht <notifications@github.com> wrote:
>I've updated this PR to use
>https://github.com/joostkremers/parsebib/pull/6 It is indeed quite a
>bit cleaner.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tmalsburg/helm-bibtex/pull/161#issuecomment-285078174

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joostkremers** [comment]
I closed https://github.com/joostkremers/parsebib/pull/6 . parsebib now gained a set of higher-level parsing functions and the ability to expand strings based on a hash table of `@string` definitions that can be passed to the relevant functions.

The README has the details, but in short: there is now a function `parsebib-parse-buffer` that returns all BibTeX items in a buffer, and there are functions for collecting all entries, `@string` or `@preamble` definitions. Those functions for which it makes sense can take an additional argument to ensure that `@string` abbreviations are expanded. When such an argument is passed, not only are `@string` abbreviations expanded, field values are also returned without enclosing braces or double quotes and sequences of newlines and spaces in field values are reduced to a single space. In essence, passing a hash table of `@string` definitions means that the .bib data is returned in such a way that it becomes suitable for displaying to the user, rather than it being returned exactly how it's present in the .bib file.

The lower-level API can still be used, of course. It now also has the ability to expand `@string` abbrevs and return the data for displaying.

**Comment by tmalsburg** [comment]
This is great, thank you.  I suppose this will allow us to simplify a bunch of things.

Do you think it would also make sense to also add resolution of crossrefs to parsebib?  Conceptually crossrefs are similar to string constants.  By resolution I mean copying fields from the crossreffed entry into the crossreffing entry.  Duplicate fields are allowed but local fields come first in the association list such that they override fields from the crossreffed fields when accessed via `assoc`.

**Comment by joostkremers** [comment]
> This is great, thank you. I suppose this will allow us to simplify a bunch of things.

Yes, instead of using a loop to read all the entries yourself, you could simply call a single function. Note, BTW, that I don't know which kind of format helm expects for its candidates list, so if you'd like me to tweak parsebib's return values in some way, just let me know. I don't have any plans for the near future to use the higher-level API for Ebib, because Ebib does its own error reporting and needs access to the line numbers in the bib file, so I can make parsebib output whatever you like.

> Do you think it would also make sense to also add resolution of crossrefs to parsebib?

Yeah, I guess that would make sense. Ebib already has such a mechanism built in, but it's in a part of the code where it doesn't really make sense. It shouldn't be too difficult to move that code to parsebib.

Would it be important for you that field values that are retrieved from xref'ed entries are marked in some way? If yes, any particular way you'd want it marked? It's important for Ebib, and right now I use a text property on the relevant string.

**Comment by tmalsburg** [comment]
Hey both, I'm currently traveling and don't have time to work on this.  I'll come back to this when I'm back home.  Best wishes!

**Comment by joostkremers** [comment]
I pushed a new version of `parsebib.el` that is able to resolve cross-references. It works slightly differently than resolving `@string` abbrevs and can be used independently from it, although it wouldn't really make sense to do so if only because `@string` abbrevs in the `crossref` field wouldn't be expanded).

Field values that are inherited from cross-referenced fields are not marked in any way (though that would be an easy change). Note that there is support for biblatex's more sophisticated inheritance system as well, though by default, BibTeX's inheritance rule is used.

Details are in the README.

**Comment by tmalsburg** [comment]
Sounds good. In helm-bibtex we don't need marking of inherited fields. They are all treated the same at this time.

**Comment by malb** [comment]
Hiya, since there's some movement in this repo I figured it's okay to send a quick ping on this PR. Anything I should do to make it mergeable?

**Comment by tmalsburg** [comment]
Hi, sorry for not taking care of this.  I hope I will have time to revisit this next week.

**Comment by tmalsburg** [comment]
Hi, I reread the conversations here and over at parsebib, had a look at the code, and conducted some simple tests.  All looks good and I merged.

The code for parsing has become rather comples and I hope we will be able to simplify it in the future using @joostkremers' new high-level functions.

For now, thanks everyone for your contributions!

**Comment by tmalsburg** [comment]
I think there is code for stripping curly braces and quotes around bibtex fields.  Do I understand correctly that that's not needed anymore because parsebib strippes these when provided with a string hash?

**Comment by tmalsburg** [comment]
In 121fb2d720e2a3a3dcdd21eedf3308431318c929 I fixed a small bug that I think is related to this.

**Comment by joostkremers** [comment]
> I think there is code for stripping curly braces and quotes around bibtex fields. Do I understand correctly that that's not needed anymore because parsebib strippes these when provided with a string hash?

Yes, that's correct. Basically, if you pass a string hash to the reading functions, the output is modified so that it becomes suitable for display: braces or double quotes are removed and multiple whitespace characters are reduced to a single space.

**Pull request merged**
