### PR TITLE
Jumping to start page of article

### PR DESCRIPTION
**Pull request by mgttlinger**
As discussed in #274 pdfs can be opened at the "right" location for journal pdfs if pdf-tools is used.

### CODE REVIEW

**Comment by tmalsburg** [comment]
Thanks for the PR!  One question: Does this feature only work with pdftools or also with Emacs' native pdf-viewer?

**Comment by tmalsburg** [comment]
Another question: If the entry is a journal article, the pages field may contain something like `146-189` but the PDF probably only contains a single article and the article will be on page one not 146.  Wouldn't the code in the PR try to jump to position 146?  Sorry if I misunderstood how it works.

**Comment by mgttlinger** [comment]
> Does this feature only work with pdftools or also with Emacs' native pdf-viewer?

Currently only pdftools given that the functions I use are from pdftools. I could look into docview and see if there is something similar there.

> If the entry is a journal article, the pages field may contain something like 146-189 but the PDF probably only contains a single article and the article will be on page one not 146. Wouldn't the code in the PR try to jump to position 146?

That is what the function `bibtex-completion-pdf-find-offset` tries to handle. It checks how many pages the pdf has and if it has fewer pages than the start page of the article it jumps to page 1 instead. This is not the perfect or most advanced method to handle this but as an initial implementation, this seemed simple and working.

**Comment by tmalsburg** [comment]
Sorry for the slow response.  I've looked at the PR again.  I suggest that we remove the code for the custom field startpage which probably no one else is using.  The two functions can then be combined into one.  Could you please also wrap long lines?  Thank you.

**Comment by mgttlinger** [comment]
I'm not sure anymore if this really makes sense. I use this feature very rarely and given that it currently only works with pdf-tools its applicability is very limited.

**Comment by tmalsburg** [comment]
Okay, in this case, I'll close this PR for now.  Thank you.

**Pull request closed without merging**
