### PR TITLE
Add a customisation for toggling of proactive reloading of bibliography, II.

### PR DESCRIPTION
**Pull request by rdiaz02**
From the change of mwlodarczak at

https://github.com/mwlodarczak/helm-bibtex/commit/4a421cae9b7d4cdb4a0933080633564b1774addb

with a minor fix and more detailed docstring.

### CODE REVIEW

**Comment by tmalsburg** [comment]
Thank you for making this PR.  Could you please provide some context? I'm wondering why anyone would not want to reload the bibliography when it was changed?

**Comment by tmalsburg** [comment]
Ah, I just saw your comment in #297.  Hm, I think the solution to reload asynchronously (in a thread) would be much nicer. Doesn't need a configuration variable and should work for everyone.  Unfortunately, I don't have to time to implement it.  There is at least one possible race condition that would have to be dealt with carefully: a second reload is triggered before the first is finished. What do you think?

**Comment by rdiaz02** [comment]
I think you are absolutely right that to reload asynchronously (in a thread) would be much nicer. But my elisp is completely rudimentary, so I would not be able to implement it.

P.S. Apologies for not having provided context in the PR.

**Comment by tmalsburg** [comment]
Thanks for the response.  I merged the PR as a stop-gap solution.  Hope we will have something better in place in the future.

**Comment by rdiaz02** [comment]
Thank you.

**Pull request merged**
