### PR TITLE
No quotes are needed when creating new helm actions

### PR DESCRIPTION
**Pull request by Titan-C**
I'm quite a ELisp beginner. But after trying to get a new action (open pdf and notes at the same time) I noticed this quotes are not needed.

### CODE REVIEW

**Comment by tmalsburg** [comment]
True, but while you are at it, could you also remove the equivalent quotes for ivify? Thank you!

**Comment by Titan-C** [comment]
Removed the ivify quotes.

**Comment by tmalsburg** [comment]
Thank you, Óscar!

**Comment by tmalsburg** [comment]
And have fun hacking elisp :-)

**Pull request merged**
